version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:3.9.0
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    command: kong migrations bootstrap
    restart: on-failure

  kong:
    image: kong:3.9.0
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:6001
      KONG_PROXY_LISTEN: 0.0.0.0:6000
      KONG_PLUGINS: bundled,callout
      KONG_LOG_LEVEL: debug
      KONG_LUA_PACKAGE_PATH: /usr/local/custom-plugins/?.lua;/usr/local/custom-plugins/?/init.lua;;
      KONG_ADMIN_GUI_URL: http://localhost:6002
      KONG_ADMIN_API_URI: http://localhost:6001
      KONG_ADMIN_GUI_API_URL: http://localhost:6001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:6002
    ports:
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
    volumes:
      - ./plugins:/usr/local/custom-plugins/kong/plugins
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10 